import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import styles from "../styles/Home.module.css";

// Server Side
export async function getStaticProps() {
  await import("../public/wasm_exec.js");

  const go = new Go();
  const mod = await WebAssembly.compile(fs.readFileSync("public/main.wasm"));
  let inst = await WebAssembly.instantiate(mod, go.importObject);
  go.run(inst);

  console.log(sum(3, 4));
  printMessage("JS calling Go and back again!", (err, message) => {
    if (err) {
      console.error(err);
      return;
    }

    console.log(message);
  });

  return { props: {} };
}

// Client Side
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>
        Home Page
      </h1>

      <h3>
        Hello
      </h3>

      <Script
        src="wasm_exec.js"
        onLoad={() => {
          const go = new Go();
          console.log(WebAssembly);
          WebAssembly.instantiateStreaming(
            fetch("main.wasm"),
            go.importObject
          ).then((wasm) => {
            // 웹 어셈블리 로딩
            go.run(wasm.instance);
          });
        }}
      />
    </div>
  );
}
